version: '3'

services:
  nginx:
    container_name: symfony_app_nginx
    build:
      context: ./
      dockerfile: docker/development/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./www/public:/var/www/public
      - ./www/var/run/php:/var/run/php
    depends_on:
      - php
    environment:
      TZ: Asia/Tokyo

  php:
    container_name: symfony_app_php
    build:
      context: ./
      dockerfile: docker/development/php/Dockerfile
    volumes:
      - ./www:/var/www:rw
      - ./www/var/run/php:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
    links:
      - database

  database:
    container_name: symfony_app_pgsql
    build:
      context: ./
      dockerfile: docker/development/database/Dockerfile
    volumes:
      - pgsql_data:/var/lib/postgresql/data:rw
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony_app_user
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    command: -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: "10k"
        max-file: "5"

  # テーブル定義
  tbls:
    container_name: symfony_app_dbdoc
    image: k1low/tbls:latest
    volumes:
      - ./:/work
    command: doc mysql://symfony_app_user:secret@symfony_app_pgsql:5432/symfony ./docs/schema --force
    profiles:
      - dbdoc

volumes:
  pgsql_data:
    driver: local
