services:
  Chanshige\HalJsonResponseBundle\EventListener\AttributeListener:
    arguments:
      $reader: '@Chanshige\HalJsonResponseBundle\Extend\AttributeReader'
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

  Chanshige\HalJsonResponseBundle\EventListener\ViewListener:
    arguments:
      $link: '@Chanshige\HalJsonResponseBundle\HalLink'
    tags:
      - { name: kernel.event_listener, event: kernel.view }

  Chanshige\HalJsonResponseBundle\Contracts\HalJsonResponseInterface:
    class: Chanshige\HalJsonResponseBundle\HalJsonResponse

  Chanshige\HalJsonResponseBundle\Extend\AttributeReader:
  Chanshige\HalJsonResponseBundle\HalLink: